//! # gRPC API
//!
//! High-performance gRPC interface for produce/consume and cluster management.
//! The protobuf definitions are compiled at build time by tonic-build.

// Include the generated protobuf code.
// This will be generated by `tonic-build` from `proto/intelstream.proto`.
// Until the proto is compiled, we provide stub types.

pub mod service;

use serde::{Deserialize, Serialize};

/// Placeholder until protobuf codegen is wired up.
/// In production, replace with: `tonic::include_proto!("intelstream");`
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProduceRequestProto {
    pub topic: String,
    pub partition: u32,
    pub key: Vec<u8>,
    pub value: Vec<u8>,
    pub headers: std::collections::HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProduceResponseProto {
    pub offset: u64,
    pub timestamp: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FetchRequestProto {
    pub topic: String,
    pub partition: u32,
    pub offset: u64,
    pub max_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FetchResponseProto {
    pub messages: Vec<MessageProto>,
    pub high_watermark: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageProto {
    pub offset: u64,
    pub key: Vec<u8>,
    pub value: Vec<u8>,
    pub timestamp: i64,
    pub headers: std::collections::HashMap<String, String>,
}
